[env:m5stack-basic]
platform = espressif32
board = m5stack-core-esp32
framework = arduino
monitor_speed = 115200
lib_extra_dirs =
  vendor/aquestalk
lib_deps =
  m5stack/M5Stack
  bblanchon/ArduinoJson@^7.4.2
